version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - services-mysql-volume:/var/lib/mysql
  kafka:
    image: 'confluentinc/cp-kafka:5.2.1'
    container_name: dataflow-kafka
    expose:
      - '9092'
    ports:
      - 9092:9092
    environment:
      - 'KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
  kafka_manager:
    image: solsson/kafka-manager
    container_name: kafkamanager
    ports:
      - 9900:9000
    links:
      - kafka
    environment:
      ZK_HOSTS: "zookeeper:2181"
  zookeeper:
    image: 'confluentinc/cp-zookeeper:5.2.1'
    container_name: dataflow-kafka-zookeeper
    expose:
      - '2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  eureka:
    image: dockerhub.webbfontaine.am:5000/paylican/reporter/eureka
    container_name: eureka
    ports:
      - 8761:8761
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
  keycloak-db:
    image: postgres
    container_name: keycloak-db
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: jboss/keycloak:9.0.2
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      #KEYCLOAK_LOGLEVEL: DEBUG
      #KEYCLOAK_HTTP_PORT: 9990
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db

volumes:
  scdf-targets: null
  dataflow-mysql-volume:
  services-mysql-volume:
  postgres-data:
  keycloak-data:
    driver: local